cyklokoalicia/OpenSourceBikeShare

connectors/smsgateway.me.php

Working connector - deviceId finder added
and few other changes

Updated smsgateway.me connector

---

actions-qrcode.php
actions-sms.php
actions-web.php
admin.php
agree.php
base.php
command.php
common.php
connectors/disabled.php
connectors/eurosms.php
connectors/loopback.php
connectors/loopback/phone.php
connectors/smsGateway.me.class.php
connectors/smsgateway.me.php
connectors/textmagic.com.php
cron.php
db.class.php
index.php
install/generate.php
install/index.php
last-usage.php
receive.php
register.php
report.php
scan.php
user-report.php

- excluded 'external', 'js', 'css' dirs
- we can discuss the style and changes here, i didn't check every change

Run php code beautifier (phpcbf with PSR2)

---

actions-sms.php
admin.php
common.php
receive.php

Please do not merge yet, I will use this PR for comments and questions

Actions sms

---

common.php

Not committing transaction resulted in agree link not saving T&C signage.

Fix transaction commit in agree link

---

actions-web.php

sql injection fix

---

actions-web.php
common.php
src/Mail/DebugMailSender.php
src/Mail/MailSenderInterface.php
src/Mail/PHPMailerMailSender.php
tests/Mail/DebugMailSenderTest.php
tests/Mail/PHPMailerSenderTest.php

Send mail via MailSenderInterface

Add MailSenderInterface

---

.gitignore
actions-sms.php
admin.php
agree.php
command.php
common.php
composer.json
cron.php
index.php
install/generate.php
install/index.php
receive.php
scan.php
src/Db/MysqliDb.php
src/SmsConnector/SmsConnectorFactory.php
src/SmsConnector/SmsGatewayConnector.php
src/SmsConnector/TextmagicSmsConnector.php
tests/Db/MysqliDbTest.php
tests/SmsConnector/SmsConnectorFactoryTest.php

Add monolog logger for logging application events

add monolog logger

---

composer.json
tests/Authentication/AuthTest.php
tests/SmsConnector/EuroSmsConnectorTest.php

using php-mock/php-mock-phpunit for code coverage of default php func

---

actions-web.php
docker-compose.yml
src/Db/MysqliDbResult.php

Fix bike rent
Increase limit for file upload via phpmyadmin

Fix bike rent

---

index.php

remove broken first april joke

---

actions-qrcode.php
docker-compose.yml
docker-data/mysql/conf/my.cnf
scan.php

Sometimes users can open link for rent bike by qr code accidentally, for example in a pocket. That's why it's additional step with approve is added

QrCode rent add additional step

---

.env
common.php
composer.json
config/services.php
src/App/Kernel.php
src/SmsConnector/AbstractConnector.php

using .env

---

actions-qrcode.php

add notice to qr rent form

---

src/Controller/PersonalStatsController.php
src/Repository/StatsRepository.php
templates/stats.html.twig
translations/messages+intl-icu.en.php

Bug fix, Enhancement
___
- Fixed potential bugs in stats calculation by replacing unsafe `reset(array_keys())` with `array_key_first()`
- Added proper handling for years with no data, showing a warning message
- Improved UI by displaying the selected year in the header
- Added new translation string for empty data state
- Enhanced template rendering with year parameter
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>PersonalStatsController.php</strong><dd><code>Add year parameter to stats template</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

personal yearly stats fixes

---

public/js/admin.js
src/Controller/Api/CouponController.php
src/Controller/Api/CreditController.php
src/Controller/Api/UserController.php
src/EventListener/ResponseEventListener.php
src/Repository/CreditRepository.php

Enhancement
___
- Standardized API responses by converting plain text responses to JSON format across multiple controllers (Coupon, Credit, User)
- Enhanced ResponseEventListener to properly handle both JSON and plain text responses
- Fixed SQL query string formatting in CreditRepository
- Improved admin interface with better search functionality and cleanup of debug code
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>CouponController.php</strong><dd><code>Convert response format to JSON structure</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

Response fix

---

config/packages/security.php
src/Controller/CommandController.php

Enhancement, Bug fix
___
- Made `command.php` accessible without authentication.
- Added logging for unauthorized access to `command.php`.
- Updated security configuration to include `command.php`.
- Enhanced `CommandController` with logging and routing annotations.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>security.php</strong><dd><code>Updated security configuration for `command.php`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
config/packages/security.php
- Added access control for `command.php` to allow anonymous access.
</details>
</td>
<td><a …

make command.php accesible without auth add logger for unathorised user

---

common.php
config/services.php
src/Event/BikeRentEvent.php
src/Event/BikeReturnEvent.php
src/Event/ManyRentEvent.php
src/EventListener/AdminNotificationEventListener.php
src/EventListener/TooManyBikeRentEventListener.php
src/Rent/AbstractRentSystem.php
src/Repository/HistoryRepository.php
translations/messages+intl-icu.en.php

Enhancement, Tests
___
- Introduced event-driven architecture for bike rental operations.
- Added new event classes: `BikeRentEvent`, `BikeReturnEvent`, and `ManyRentEvent`.
- Implemented `TooManyBikeRentEventListener` to monitor excessive bike rentals.
- Removed legacy `checktoomany` function and integrated new event-based logic.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td><strong>common.php</strong><dd><code>Removed legacy `checktoomany` function for excessive rentals.</code></dd></td>
<td><a href="https://github.com/cyklokoalicia/OpenSourceBikeShare/pull/222/files#diff-e097171af35afc2da471ac9f44bd313783d077a0a97bcc61205278d83413a47a">+0/-39</a>&nbsp …

add event listener on many rents during some period

---

.env.dist
config/packages/security.php
config/routes.php
config/services.php
src/App/Entity/ApiServiceUser.php
src/App/Security/ApiTokenAuthenticator.php
src/Controller/Api/StandController.php
tests/Application/Controller/Api/Stand/StandMarkersTest.php

Enhancement
___
- Add token-based API authentication for external services
- Create new API endpoint for stand markers with token auth
- Implement role hierarchy and access control for API users
- Add comprehensive test coverage for token authentication
___
```mermaid
flowchart LR
A["External Service"] -- "Bearer Token" --> B["ApiTokenAuthenticator"]
B -- "Validates Token" --> C["ApiServiceUser"]
C -- "ROLE_API" --> D["API Endpoint"]
D -- "Returns Data" --> E["Stand Markers"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>security.php</strong><dd><code>Configure token authentication and role …

new api access with token

---

src/Controller/AdminController.php
src/Controller/Api/BikeController.php
src/Controller/Api/CouponController.php
src/Controller/Api/CreditController.php
src/Controller/Api/ReportController.php
src/Controller/Api/StandController.php
src/Controller/Api/UserController.php
src/Controller/CommandController.php
src/Controller/EmailConfirmController.php
src/Controller/HomeController.php
src/Controller/PersonalStatsController.php
src/Controller/PhoneConfirmController.php
src/Controller/QrCodeGeneratorController.php
src/Controller/RegisterController.php
src/Controller/ScanController.php
src/Controller/SecurityController.php
src/Controller/SmsRequestController.php
tests/Application/Controller/Api/Stand/StandMarkersTest.php
tests/Integration/Rent/RentSystemTest.php
tests/Unit/SmsCommand/DelNoteCommandTest.php
tests/Unit/SmsCommand/FreeCommandTest.php
tests/Unit/SmsCommand/ListCommandTest.php
tests/Unit/SmsCommand/UnTagCommandTest.php

Enhancement
___
- Migrate from Symfony Route annotations to PHP attributes
- Update import statements across all controllers
- Modernize route configuration syntax
- Improve code formatting and PSR compliance
___
```mermaid
flowchart LR
A["Route Annotations"] --> B["PHP Attributes"]
C["@Route docblocks"] --> D["#[Route] attributes"]
E["Annotation imports"] --> F["Attribute imports"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>17 files</summary><table>
<tr>
<td><strong>AdminController.php</strong><dd><code>Convert admin route to PHP attribute</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Update route desc

---

src/App/Security/UserProvider.php
tests/Integration/Rent/RentSystemTest.php

Bug fix
___
- Add support for `ApiServiceUser` in user provider
- Fix `refreshUser` method to handle API service users
- Update `supportsClass` method for proper user type validation
___
```mermaid
flowchart LR
A["UserProvider"] --> B["refreshUser method"]
A --> C["supportsClass method"]
B --> D["Handle ApiServiceUser"]
C --> E["Support ApiServiceUser class"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>UserProvider.php</strong><dd><code>Add ApiServiceUser support to UserProvider</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …

Fix user Provider

---

src/Controller/SecurityController.php
templates/security/reset_password.html.twig

Bug fix
___
- Add error handling for invalid phone number format
- Display error messages in reset password template
- Redirect user back to form on validation errors
___
```mermaid
flowchart LR
A["User submits phone number"] --> B["Validate phone number"]
B --> C["Invalid format?"]
C -->|Yes| D["Show error message"]
C -->|No| E["Process reset request"]
D --> F["Redirect to reset form"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>SecurityController.php</strong><dd><code>Add invalid phone number error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Fix restore password form

---

public/js/admin.js

Enhancement
___
- Add bike code setting functionality via admin interface
- Implement SMS command for code changes
- Update history tracking and statistics filtering
- Add comprehensive test coverage
___
```mermaid
flowchart LR
Admin["Admin User"] --> WebAPI["Web API /api/bike/{id}/code"]
Admin --> SMS["SMS Command 'CODE'"]
WebAPI --> BikeRepo["BikeRepository.updateBikeCode()"]
SMS --> CodeCommand["CodeCommand Handler"]
CodeCommand --> BikeRepo
BikeRepo --> Database["bikes.currentCode"]
WebAPI --> History["History Logging"]
SMS --> History
History --> Database2["history table"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration …

Fix bike usage display
